export const types = [
  "romancebook",
  "bestseller",
  "engineeringbook",
  "medicalbook",
  "thrillbook",
  "politicsbook",
  "religiousbook",
  "historybook",
  "healthbook",
  "computerbook",
  "scifibook",
  "newrelease",
];
export const links = [
  "https://www.amazon.com/Best-Sellers-Books-Romance/zgbs/books/23/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Computers-Technology/zgbs/books/5/ref=zg_bs_nav_books_1_283155",
  "https://www.amazon.com/Best-Sellers-Books-Engineering-Transportation/zgbs/books/173507/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Medical-Books/zgbs/books/173514/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Mystery-Thriller-Suspense/zgbs/books/18/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Politics-Social-Sciences/zgbs/books/3377866011/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Religion-Spirituality/zgbs/books/22/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-History/zgbs/books/9/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Health-Fitness-Dieting/zgbs/books/10/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Computers-Technology/zgbs/books/5/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/Best-Sellers-Books-Science-Fiction-Fantasy/zgbs/books/25/ref=zg_bs_nav_books_1",
  "https://www.amazon.com/gp/new-releases/books/?ie=UTF8&ref_=sv_b_2",
];
